"""Every LinkSnap feature route, one method each — generated by apigen from
backend/openapi.json. Do not edit by hand; regenerate after the API changes.

Reach them as ``client.api.<area>_<action>(...)``. Each call goes through the
client's own ``_apigen_request`` (its sign-in and response envelope).
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional


class GeneratedApi:
    """All 52 feature routes of the LinkSnap API."""

    def __init__(self, client: Any) -> None:
        self._client = client

    def _call(self, method: str, path: str, query: Dict[str, Any], body: Optional[Dict[str, Any]]) -> Any:
        query = {k: v for k, v in query.items() if v is not None}
        return self._client._apigen_request(method, path, query=query or None, body=body)

    # A file upload: the form fields and the files, sent by the client as multipart/form-data.
    def _call_form(self, method: str, path: str, query: Dict[str, Any], form: Dict[str, Any], files: Dict[str, Any]) -> Any:
        query = {k: v for k, v in query.items() if v is not None}
        return self._client._apigen_request(method, path, query=query or None, form=form, files=files)

    def audit_log_list(self, *, action: Optional[Any] = None, cursor: Optional[Any] = None, limit: Optional[Any] = None) -> Any:
        """List audit log (GET /api/v1/audit-log)."""
        return self._call("GET", f"/api/v1/audit-log", {"action": action, "cursor": cursor, "limit": limit}, None)

    def billing_cancel(self) -> Any:
        """Cancel the active paid subscription at period end. (POST /api/v1/billing/cancel)."""
        return self._call("POST", f"/api/v1/billing/cancel", {}, None)

    def billing_checkout(self, *, currency: Optional[Any] = None, plan: Optional[Any] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a Plugipay checkout session for the selected LinkSnap tier. (POST /api/v1/billing/checkout).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if currency is not None:
            payload["currency"] = currency
        if plan is not None:
            payload["plan"] = plan
        return self._call("POST", f"/api/v1/billing/checkout", {}, payload)

    def billing_downgrade(self, *, plan: Optional[Any] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """/billing/webhook/storlaunch was the legacy receiver back when LinkSnap routed checkout through Storlaunch's Midtrans wrapper. (POST /api/v1/billing/downgrade).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if plan is not None:
            payload["plan"] = plan
        return self._call("POST", f"/api/v1/billing/downgrade", {}, payload)

    def billing_history(self, *, cursor: Optional[Any] = None, limit: Optional[Any] = None) -> Any:
        """Billing history (paginated) (GET /api/v1/billing/history)."""
        return self._call("GET", f"/api/v1/billing/history", {"cursor": cursor, "limit": limit}, None)

    def billing_invoices(self, *, cursor: Optional[Any] = None, limit: Optional[Any] = None) -> Any:
        """Alias for history (GET /api/v1/billing/invoices)."""
        return self._call("GET", f"/api/v1/billing/invoices", {"cursor": cursor, "limit": limit}, None)

    def billing_plan(self) -> Any:
        """Return current user's plan with all limits (GET /api/v1/billing/plan)."""
        return self._call("GET", f"/api/v1/billing/plan", {}, None)

    def billing_plans(self) -> Any:
        """Return all 3 plans with IDR prices (public, no auth needed) (GET /api/v1/billing/plans)."""
        return self._call("GET", f"/api/v1/billing/plans", {}, None)

    def billing_subscription(self) -> Any:
        """Return current subscription details (GET /api/v1/billing/subscription)."""
        return self._call("GET", f"/api/v1/billing/subscription", {}, None)

    def billing_usage(self) -> Any:
        """Return current usage vs plan limits (GET /api/v1/billing/usage)."""
        return self._call("GET", f"/api/v1/billing/usage", {}, None)

    def domains_create(self, *, domain: Optional[Any] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Add custom domain (POST /api/v1/domains).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if domain is not None:
            payload["domain"] = domain
        return self._call("POST", f"/api/v1/domains", {}, payload)

    def domains_delete(self, id_: str) -> Any:
        """Remove domain (DELETE /api/v1/domains/{id})."""
        return self._call("DELETE", f"/api/v1/domains/{_q(id_)}", {}, None)

    def domains_get(self, id_: str) -> Any:
        """Get single domain (GET /api/v1/domains/{id})."""
        return self._call("GET", f"/api/v1/domains/{_q(id_)}", {}, None)

    def domains_list(self) -> Any:
        """List custom domains (GET /api/v1/domains)."""
        return self._call("GET", f"/api/v1/domains", {}, None)

    def domains_verify(self, id_: str) -> Any:
        """Verify domain DNS (POST /api/v1/domains/{id}/verify)."""
        return self._call("POST", f"/api/v1/domains/{_q(id_)}/verify", {}, None)

    def links_bulk(self, *, action: Optional[Any] = None, ids: Optional[Any] = None, tag: Optional[Any] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Bulk operations (POST /api/v1/links/bulk).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if action is not None:
            payload["action"] = action
        if ids is not None:
            payload["ids"] = ids
        if tag is not None:
            payload["tag"] = tag
        return self._call("POST", f"/api/v1/links/bulk", {}, payload)

    def links_create(self, *, expires_at: Optional[Any] = None, max_clicks: Optional[Any] = None, slug: Optional[Any] = None, tags: Optional[Any] = None, url: Optional[Any] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create link (POST /api/v1/links).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if expires_at is not None:
            payload["expiresAt"] = expires_at
        if max_clicks is not None:
            payload["maxClicks"] = max_clicks
        if slug is not None:
            payload["slug"] = slug
        if tags is not None:
            payload["tags"] = tags
        if url is not None:
            payload["url"] = url
        return self._call("POST", f"/api/v1/links", {}, payload)

    def links_delete(self, id_: str) -> Any:
        """Delete link (DELETE /api/v1/links/{id})."""
        return self._call("DELETE", f"/api/v1/links/{_q(id_)}", {}, None)

    def links_export(self, *, format_: Optional[Any] = None) -> Any:
        """Export links - MUST be before /:id to avoid matching 'export' as an ID (GET /api/v1/links/export)."""
        return self._call("GET", f"/api/v1/links/export", {"format": format_}, None)

    def links_get(self, id_: str) -> Any:
        """Get link by ID or slug (GET /api/v1/links/{id})."""
        return self._call("GET", f"/api/v1/links/{_q(id_)}", {}, None)

    def links_import(self, *, dry_run: Optional[Any] = None, links: Optional[Any] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Import links (JSON body) (POST /api/v1/links/import).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if dry_run is not None:
            payload["dryRun"] = dry_run
        if links is not None:
            payload["links"] = links
        return self._call("POST", f"/api/v1/links/import", {}, payload)

    def links_list(self, *, cursor: Optional[Any] = None, limit: Optional[Any] = None, order: Optional[Any] = None, q: Optional[Any] = None, sort: Optional[Any] = None, status: Optional[Any] = None, tag: Optional[Any] = None) -> Any:
        """List links (GET /api/v1/links)."""
        return self._call("GET", f"/api/v1/links", {"cursor": cursor, "limit": limit, "order": order, "q": q, "sort": sort, "status": status, "tag": tag}, None)

    def links_stats(self, id_: str, *, from_: Optional[Any] = None, to: Optional[Any] = None) -> Any:
        """List stats (GET /api/v1/links/{id}/stats)."""
        return self._call("GET", f"/api/v1/links/{_q(id_)}/stats", {"from": from_, "to": to}, None)

    def links_stats_export(self, id_: str, *, format_: Optional[Any] = None, from_: Optional[Any] = None, to: Optional[Any] = None) -> Any:
        """Get link stats (GET /api/v1/links/{id}/stats/export)."""
        return self._call("GET", f"/api/v1/links/{_q(id_)}/stats/export", {"format": format_, "from": from_, "to": to}, None)

    def links_update(self, id_: str, *, expires_at: Optional[Any] = None, max_clicks: Optional[Any] = None, slug: Optional[Any] = None, status: Optional[Any] = None, tags: Optional[Any] = None, url: Optional[Any] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Update link (PATCH /api/v1/links/{id}).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if expires_at is not None:
            payload["expiresAt"] = expires_at
        if max_clicks is not None:
            payload["maxClicks"] = max_clicks
        if slug is not None:
            payload["slug"] = slug
        if status is not None:
            payload["status"] = status
        if tags is not None:
            payload["tags"] = tags
        if url is not None:
            payload["url"] = url
        return self._call("PATCH", f"/api/v1/links/{_q(id_)}", {}, payload)

    def qr_codes_create(self, *, expires_at: Optional[Any] = None, link_id: Optional[Any] = None, logo_run_ref: Optional[Any] = None, max_scans: Optional[Any] = None, style_config: Optional[Any] = None, tags: Optional[Any] = None, title: Optional[Any] = None, url: Optional[Any] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create QR code (POST /api/v1/qr-codes).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if expires_at is not None:
            payload["expiresAt"] = expires_at
        if link_id is not None:
            payload["linkId"] = link_id
        if logo_run_ref is not None:
            payload["logoRunRef"] = logo_run_ref
        if max_scans is not None:
            payload["maxScans"] = max_scans
        if style_config is not None:
            payload["styleConfig"] = style_config
        if tags is not None:
            payload["tags"] = tags
        if title is not None:
            payload["title"] = title
        if url is not None:
            payload["url"] = url
        return self._call("POST", f"/api/v1/qr-codes", {}, payload)

    def qr_codes_delete(self, id_: str) -> Any:
        """Delete QR code (DELETE /api/v1/qr-codes/{id})."""
        return self._call("DELETE", f"/api/v1/qr-codes/{_q(id_)}", {}, None)

    def qr_codes_download(self, id_: str, *, format_: Optional[Any] = None, token: Optional[Any] = None) -> Any:
        """Download QR code image — MUST be before /:id Supports both Authorization header and ?token= query parameter (GET /api/v1/qr-codes/{id}/download)."""
        return self._call("GET", f"/api/v1/qr-codes/{_q(id_)}/download", {"format": format_, "token": token}, None)

    def qr_codes_download_token(self, id_: str) -> Any:
        """Generate download token — MUST be before /:id (POST /api/v1/qr-codes/{id}/download-token)."""
        return self._call("POST", f"/api/v1/qr-codes/{_q(id_)}/download-token", {}, None)

    def qr_codes_get(self, id_: str) -> Any:
        """Get single QR code (GET /api/v1/qr-codes/{id})."""
        return self._call("GET", f"/api/v1/qr-codes/{_q(id_)}", {}, None)

    def qr_codes_list(self, *, cursor: Optional[Any] = None, limit: Optional[Any] = None, link_id: Optional[Any] = None, q: Optional[Any] = None, status: Optional[Any] = None, tag: Optional[Any] = None) -> Any:
        """List QR codes (GET /api/v1/qr-codes)."""
        return self._call("GET", f"/api/v1/qr-codes", {"cursor": cursor, "limit": limit, "linkId": link_id, "q": q, "status": status, "tag": tag}, None)

    def qr_codes_stats(self, id_: str, *, from_: Optional[Any] = None, to: Optional[Any] = None) -> Any:
        """Get QR code stats — MUST be before /:id (GET /api/v1/qr-codes/{id}/stats)."""
        return self._call("GET", f"/api/v1/qr-codes/{_q(id_)}/stats", {"from": from_, "to": to}, None)

    def qr_codes_update(self, id_: str, *, expires_at: Optional[Any] = None, logo_run_ref: Optional[Any] = None, max_scans: Optional[Any] = None, status: Optional[Any] = None, style_config: Optional[Any] = None, tags: Optional[Any] = None, title: Optional[Any] = None, url: Optional[Any] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Update QR code (PATCH /api/v1/qr-codes/{id}).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if expires_at is not None:
            payload["expiresAt"] = expires_at
        if logo_run_ref is not None:
            payload["logoRunRef"] = logo_run_ref
        if max_scans is not None:
            payload["maxScans"] = max_scans
        if status is not None:
            payload["status"] = status
        if style_config is not None:
            payload["styleConfig"] = style_config
        if tags is not None:
            payload["tags"] = tags
        if title is not None:
            payload["title"] = title
        if url is not None:
            payload["url"] = url
        return self._call("PATCH", f"/api/v1/qr-codes/{_q(id_)}", {}, payload)

    def qr_codes_upload_logo(self, *, logo: Any) -> Any:
        """Upload a logo for the QR code's center (on plans with qrLogoEnabled — every plan today) (POST /api/v1/qr-codes/upload-logo).
        
        Sent as multipart/form-data. A file is bytes, a binary file object, or a
        (filename, content[, content_type]) tuple; the other fields are keyword arguments."""
        _form: Dict[str, Any] = {}
        _files: Dict[str, Any] = {}
        _files["logo"] = logo
        return self._call_form("POST", f"/api/v1/qr-codes/upload-logo", {}, _form, _files)

    def tags_create(self, *, name: Optional[Any] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create tag (POST /api/v1/tags).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if name is not None:
            payload["name"] = name
        return self._call("POST", f"/api/v1/tags", {}, payload)

    def tags_delete(self, id_: str) -> Any:
        """Detaches it from every link and QR code. (DELETE /api/v1/tags/{id})."""
        return self._call("DELETE", f"/api/v1/tags/{_q(id_)}", {}, None)

    def tags_list(self) -> Any:
        """List tags (GET /api/v1/tags)."""
        return self._call("GET", f"/api/v1/tags", {}, None)

    def tags_update(self, id_: str, *, name: Optional[Any] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Rename tag — the tag keeps its id, so every link and QR code that carries it follows the rename for free (implicit m2m join rows key on the id, not the name). (PATCH /api/v1/tags/{id}).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if name is not None:
            payload["name"] = name
        return self._call("PATCH", f"/api/v1/tags/{_q(id_)}", {}, payload)

    def webhooks_create(self, *, events: Optional[Any] = None, url: Optional[Any] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create endpoint — returns the whsec_ secret once. (POST /api/v1/webhooks).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if events is not None:
            payload["events"] = events
        if url is not None:
            payload["url"] = url
        return self._call("POST", f"/api/v1/webhooks", {}, payload)

    def webhooks_delete(self, id_: str) -> Any:
        """Remove endpoint. (DELETE /api/v1/webhooks/{id})."""
        return self._call("DELETE", f"/api/v1/webhooks/{_q(id_)}", {}, None)

    def webhooks_list(self) -> Any:
        """List endpoints (never includes the secret). (GET /api/v1/webhooks)."""
        return self._call("GET", f"/api/v1/webhooks", {}, None)

    def webhooks_update(self, id_: str, *, active: Optional[Any] = None, events: Optional[Any] = None, url: Optional[Any] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Pause / resume delivery, or edit the endpoint's url / events. (PATCH /api/v1/webhooks/{id}).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if active is not None:
            payload["active"] = active
        if events is not None:
            payload["events"] = events
        if url is not None:
            payload["url"] = url
        return self._call("PATCH", f"/api/v1/webhooks/{_q(id_)}", {}, payload)

    def workspaces_create(self, *, name: Optional[Any] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create new workspace (POST /api/v1/workspaces).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if name is not None:
            payload["name"] = name
        return self._call("POST", f"/api/v1/workspaces", {}, payload)

    def workspaces_create_current_members(self, *, email: Optional[Any] = None, role: Optional[Any] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Invite member (POST /api/v1/workspaces/current/members).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if email is not None:
            payload["email"] = email
        if role is not None:
            payload["role"] = role
        return self._call("POST", f"/api/v1/workspaces/current/members", {}, payload)

    def workspaces_current(self) -> Any:
        """Get active workspace details (GET /api/v1/workspaces/current)."""
        return self._call("GET", f"/api/v1/workspaces/current", {}, None)

    def workspaces_current_members(self) -> Any:
        """List members (GET /api/v1/workspaces/current/members)."""
        return self._call("GET", f"/api/v1/workspaces/current/members", {}, None)

    def workspaces_current_stats(self, *, from_: Optional[Any] = None, to: Optional[Any] = None) -> Any:
        """Workspace stats (GET /api/v1/workspaces/current/stats)."""
        return self._call("GET", f"/api/v1/workspaces/current/stats", {"from": from_, "to": to}, None)

    def workspaces_delete_current_members(self, id_: str) -> Any:
        """Remove member (DELETE /api/v1/workspaces/current/members/{id})."""
        return self._call("DELETE", f"/api/v1/workspaces/current/members/{_q(id_)}", {}, None)

    def workspaces_list(self) -> Any:
        """Huudis is the source of truth. (GET /api/v1/workspaces)."""
        return self._call("GET", f"/api/v1/workspaces", {}, None)

    def workspaces_switch(self, *, workspace_id: Optional[Any] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Switch active workspace (POST /api/v1/workspaces/switch).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if workspace_id is not None:
            payload["workspaceId"] = workspace_id
        return self._call("POST", f"/api/v1/workspaces/switch", {}, payload)

    def workspaces_update_current(self, *, name: Optional[Any] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Update active workspace (PATCH /api/v1/workspaces/current).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if name is not None:
            payload["name"] = name
        return self._call("PATCH", f"/api/v1/workspaces/current", {}, payload)

    def workspaces_update_current_members(self, id_: str, *, role: Optional[Any] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Change a member's role. (PATCH /api/v1/workspaces/current/members/{id}).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if role is not None:
            payload["role"] = role
        return self._call("PATCH", f"/api/v1/workspaces/current/members/{_q(id_)}", {}, payload)


def _q(value: Any) -> str:
    from urllib.parse import quote

    return quote(str(value), safe="")
